query CheckAnyUserExists @auth(level: PUBLIC) {
  users(limit: 1) {
    id
  }
}

query GetUser($id: String!) @auth(level: PUBLIC) {
  user(id: $id) {
    id
    email
    role
    status
  }
}

query GetAllUsers @auth(level: PUBLIC) {
  users {
    id
    email
    role
    status
  }
}
